[package]
name = "cards"
version = "0.1.0"
edition = "2018"
authors = ["Joep de Ligt <public.git@biodata.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = "*"
